# Generated by Django 4.1.7 on 2023-04-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("slno", models.IntegerField()),
                (
                    "rollno",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("sname", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Studentdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=30)),
                ("contactnumber", models.IntegerField()),
                ("teacher_name", models.CharField(max_length=20)),
                (
                    "sname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacherdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.IntegerField()),
                ("subject", models.CharField(max_length=15, unique=True)),
                (
                    "teacher_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.studentdetails",
                    ),
                ),
            ],
        ),
    ]
