# Generated by Django 4.1.7 on 2023-04-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="contactnumber",
            field=models.CharField(max_length=15),
        ),
    ]
